Rewritten NNDescent algorithm using matrices instead of dictionaries.

TODO: Remove for-loops where possible.

In [1]:
import torch
import time
import matplotlib.pyplot  as plt
#from collections import defaultdict

class NNDescent:
  def __init__(self, data, k=2, trees=5, init=2, leaf_multiplier=1):
    # The data is a (N x d) matrix with N instances of d-dimensional points
    self.data = data
    N = data.shape[0]
    self.k = k
    self.numtrees = trees
    
    # A 2D tensor representing a directed graph.
    # The value a = graph[i,j] represents an edge from point x_i to x_a.
    self.graph = torch.zeros(size=[N, k], dtype=torch.long)
    
    # Initialize graph randomly or with forest
    if init == 1:
      self.initialize_graph_randomly()
    elif init == 2:
      self.initialize_graph_big_random(data)
    elif init == 3:
      self.leaves = self.initialize_graph_forest(data, leaf_multiplier)
    
#     accuracy, _ = init_accuracy(data,self.graph,torch.zeros([N, k]))
#     print('Initial Accuracy: ',accuracy)
    
    # A set of tuples (i,j) of indices for which the distance has already been calculated.
    self.explored_edges = set()

    # A 2D tensor representing the distance between point x_i and x_graph[i,j]
    self.k_distances = torch.zeros([N, k])
    self.calculate_all_distances()
    

  def initialize_graph_randomly(self):
    '''
    Initializes self.graph with random values such that each point has k distinct neighbors
    '''
    N, k = self.graph.shape
    # Initialize graph randomly, removing self-loops
    self.graph = torch.randint(high = N-1, size=[N,k], dtype=torch.long)
    row_indices = torch.arange(N).unsqueeze(1).repeat(1,k)
    self.graph[self.graph>=row_indices] += 1

  def initialize_graph_big_random(self, data):
    '''
    Initializes self.graph randomly, but with more neighbours at the start
    '''
    N, k = self.graph.shape
    temp_graph = torch.tensor([])
        
    # make 'trees', combine into giant graph with each element (row) having k * num_trees neighbours
    # this is a small for loop - numtrees and k << datapoints
    for j in range(self.numtrees):
      tree_graph = torch.tensor([])
      for i in range(k):
        tree_graph = torch.cat((tree_graph,torch.randperm(N)),0) # generate randomly shuffled list of N indices
      tree_graph = tree_graph.reshape(-1,k) # creates a N x k tensor with N indices, each appearing k times. This represents 1 'tree'
      temp_graph = torch.cat((temp_graph,tree_graph),1) # combine into giant N x (k*num_trees) tensor. This represents the forest
    
    # find KNN for each row in giant graph
    # TODO - implement the below without a for loop
    for i, row in enumerate(temp_graph):
      temp_row = torch.unique(row).type(torch.LongTensor) # remove duplicates
      temp_row = temp_row[temp_row != i] # remove self
      
      temp_points = data[temp_row,:] # pick out elements from dataset
      distances = dist_bulk(temp_points,data[i]) # Euclidean distances
      indices = distances.topk(k=self.k, largest=False).indices # find indices of KNN
      self.graph[i] = temp_row[indices] # assign KNN to graph
      
  def initialize_graph_forest(self, data, leaf_multiplier):
    '''
    Initializes self.graph with a forest of random trees, such that each point has k distinct neighbors
    '''
    N, k = self.graph.shape
    dim = data.shape[1]
    
    temp_graph = torch.tensor(())
    for j in range(self.numtrees):
      # Create trees, obtain leaves
      t = tree(data, k = k*leaf_multiplier)
      
      # Create temporary graph, 1 for each tree
      # Leaves are of uneven size; select smallest leaf size as graph size
      cols = min([len(leaf) for leaf in t.leaves])
      rows = len(t.leaves)
      tree_graph = torch.zeros((N, cols))
      leaves = torch.tensor(())
      idx_update = torch.tensor(())
      
      # Update graph using leaves
      for leaf in t.leaves:
        temp_idx = torch.as_strided(torch.tensor(leaf).repeat(1,2),size=[len(leaf),cols],stride=[1,1],storage_offset=1)
        tree_graph[leaf,:] = temp_idx.float() # update graph. a lot of overwriting
#         idx_update = torch.cat((idx_update,temp_idx), 0)
#         leaves = torch.cat((leaves,torch.tensor(leaf)), 0)
#       leaves = leaves.unique().long()
#       tree_graph[leaves,:] = idx_update.float()
      # Concatenate all graphs from all trees into 1 giant graph
      temp_graph = torch.cat((temp_graph,tree_graph), 1)
    
    warning_count = 0 # number of indices for which some neighbours are random
    # find KNN for each row in giant graph
    # TODO - implement the below without a for loop
    for i, row in enumerate(temp_graph):
      temp_row = torch.unique(row).type(torch.LongTensor) # remove duplicates
      temp_row = temp_row[temp_row != i] # remove self
      
      temp_points = data[temp_row,:] # pick out elements from dataset
      d=((data[i].reshape(1,dim).unsqueeze(1)-temp_points.unsqueeze(0))**2).sum(-1)
      distances, indices = torch.sort(d,dim=1)
      indices = indices.flatten()[:k]
      
      indices = temp_row[indices]
      
      # pad with random indices if there are not enough neighbours
      warning = False # warning flag
      while len(indices) < k:
        pad = torch.randint(high = N-1, size=[k-len(indices),], dtype=torch.long)
        indices = torch.cat((indices,pad))
        indices = torch.unique(indices).type(torch.LongTensor) # remove duplicates
        indices = indices[indices != i] # remove self
        warning = True

      self.graph[i] = indices # assign KNN to graph
      
      if warning:
        warning_count += 1
    
    if warning_count:
      print("WARNING!",warning_count," INDICES ARE RANDOM!")
        
  def calculate_all_distances(self):
    '''
    Updates the distances (self.k_distances) of the edges found in self.graph.
    '''
    # Note: Start with for loop for simplicity. TODO: Try to remove loop.
    for i, row in enumerate(self.graph):
      # Indices of current k neighbors in self.graph
      neighbor_indices = [(i,int(r)) for r in row]

      # The distances of those neighbors are saved in k_distances
      self.k_distances[i] = torch.Tensor([dist(self.data[a],self.data[b]) for a,b in neighbor_indices])

      # Add pairs to explored_edges set
      self.explored_edges.update(neighbor_indices) 
    

  def update_graph(self, iter=5):
    '''
      Updates the graph using algorithm: https://pynndescent.readthedocs.io/en/latest/how_pynndescent_works.html
    '''
    # [STEP 1: Start with random graph.] Iterate
    start = time.time()
    for it in range(iter):
#       print("Iteration number",it,"with average distance of",torch.mean(self.k_distances).item(),"Took", time.time()-start,"seconds.")
      has_changed = False

      # [STEP 2: For each node:] (TODO: Investigate whether this can be vectorized.)
      for i, neighbors in enumerate(self.graph):
        # Distances of current neighbors
        dist_current_neighbors = self.k_distances[i]

        # [STEP 3: Measure distance from the node to the neighbors of its neighbors]
        # Find neighbors of neighbors
        potential_neighbors = {a.item() for a in self.graph[neighbors].flatten() \
                               if a not in neighbors and a!=i and (i,int(a)) not in self.explored_edges}
        potential_distances = torch.Tensor([dist(self.data[i],self.data[n]) for n in potential_neighbors])
        self.explored_edges.update([(i,int(r)) for r in potential_neighbors])

        # Concatenate potential neighbors to list of neighbors (indices and distances)
        cat_idx = torch.cat([neighbors, torch.Tensor(list(potential_neighbors))])
        cat_dist = torch.cat([self.k_distances[i], potential_distances])

        # [STEP 4: If any are closer, then update the graph accordingly, and only keep the k closest]
        # Sort using torch.sort(), which also returns sorted indices
        dist_sorted, idx = torch.sort(cat_dist)
        if torch.max(idx[:self.k]) >= self.k:
          has_changed = True
          self.graph[i] = cat_idx[idx[:self.k]]
          self.k_distances[i] = dist_sorted[:self.k]
        
      # [STEP 5: If any changes were made, repeat iteration, otherwise stop]
#       if not has_changed:
#         print("Nothing changed in iteration",it)
#         break
#     print("Done.")

  def k_nearest_graph_search(self,X,max_num_steps = 100):
    '''
    Gets the k nearest neighbors of input x according to the graph, using this algorithm:
      https://pynndescent.readthedocs.io/en/latest/how_pynndescent_works.html#Searching-using-a-nearest-neighbor-graph
    Input: 
      x - a torch tensor of shape (N,d), where N is the number of dimentions of the input data.
    Output:
      The indices of the k nearest neighbors according using graph search with random initialization.
    '''

    # N datapoints of dimension d
    N, d = X.shape
    # Boolean mask to keep track of those points whose search is still ongoing
    is_active = (torch.ones(N)==1)
    
    # Random initialization for starting points of search. (TODO: replace with tree initialization)
    candidate_idx = torch.randint(high=len(self.data),size=[N, k+1], dtype=torch.long)
    
    # Note that n.data[candidate_idx] has shape N x (k+1) x d, and X has shape N x d
    # Sort the candidates by distance from X
    distances = ((self.data[candidate_idx] - X.unsqueeze(1))**2).sum(-1)
    sorted, idx = torch.sort(distances, dim=1)
    candidate_idx = torch.gather(candidate_idx, dim=1,index=idx)
    
    # Track the nodes we have explored already, in N x num_explored tensor
    num_explored = self.k*2
    explored = torch.full(size=[N,num_explored],fill_value=-1)

    start = time.time()
    # The initialization of candidates and explored set is done. Now we can search.
    count = 0
    while count < max_num_steps:
        print("Step",count,"- Search is completed for",1-torch.mean(1.0*is_active).item(),"- this step took",time.time()-start,"s")
        start=time.time()
    
        # [2. Look at nodes connected by an edge to the best untried node in graph]
        # diff_bool.shape is (M, k+1, num_explored), where M is the number of active searches
        diff_bool = (candidate_idx[is_active].unsqueeze(2) - explored[is_active].unsqueeze(1) == 0)
        in_explored = torch.any(diff_bool, dim=2)
        # batch_active is true for those who haven't been fully explored in the current batch
        batch_active = ~torch.all(in_explored[:,:-1], dim=1)

        # Update is_active mask. If none are active, break search
        is_active[is_active] = batch_active
        if not is_active.any():
            break

        # first_unexplored has indices of first unexplored element per row
        first_unexplored = torch.max(~in_explored[batch_active],dim=1)[1].unsqueeze(1) 
        # Unexplored nodes to be expanded
        unexplored_idx = torch.gather(candidate_idx[is_active], dim=1, index=first_unexplored).squeeze(-1)
        explored[is_active,(count%num_explored)] = unexplored_idx
    
        # [3. Add all these nodes to our potential candidate pool]
        # Add neighbors of the first unexplored point to the list of candidates
        expanded_idx = torch.cat((self.graph[unexplored_idx],candidate_idx[is_active]), dim=1) 
    
        # To avoid repeats, we use Hudson's unwanted_indices method to find repeats
        expanded_idx = torch.sort(expanded_idx)[0]
        shift = torch.cat((torch.full((len(expanded_idx),1),-1),torch.sort(expanded_idx,dim=1)[0][:,:-1]),dim=1)
        unwanted_indices = (expanded_idx==shift)
    
        # [4. Sort by closeness].
        distances = ((self.data[expanded_idx] - X[is_active].unsqueeze(1))**2).sum(-1)
        distances[unwanted_indices] += float('inf')
        sorted, idx = torch.sort(distances,dim=1)
        expanded_idx = torch.gather(expanded_idx,dim=1,index=idx)
    
        # [5. Truncate to k+1 best]
        candidate_idx[is_active] = expanded_idx[:,:(self.k+1)] 
        
        # [6. Return to step 2. If we have already tried all candidates in pool, we stop in the if not unexplored]
        count += 1
    
    # Return the k candidates
    print("Graph search finished after",count,"steps")
    return candidate_idx[:,:-1]

  def predict(self,x):
    '''
    Predict output using tree. Hasn't been implemented yet. Needs labels y.
    '''
    pass
    
def dist(x,y):
  # Square of euclidian distance. Skip the root for faster computation.
  return torch.sum((x-y)**2)

def dist_bulk(x,y):
  # Square of euclidian distance. Skip the root for faster computation.
  # For datasets
  return ((x-y)**2).sum(-1)

class tree:
  '''
  Random projection tree class that splits the data evenly per split
  Each split is performed by calculating the projection distance of each datapoint to a random unit vector
  The datapoints are then split by the median of of these projection distances
  The indices of the datapoints are stored in tree.leaves, as a nested list
  '''
  def __init__(self, x, k=5):
    self.min_size = 2*k-1
    self.leaves = []
    self.sizes = []
    self.big_leaves = [] # leaves at depth = 5
    indices = torch.arange(x.shape[0])
    self.tree = self.make_tree(x, indices, depth = 0)

  def make_tree(self, x, indices, depth):
    if depth == 5: # add to big_leaves if depth=5
      self.big_leaves.append(int(indices[0]))
    if x.shape[0] > self.min_size:
      v = self.choose_rule(x)
      distances = torch.tensordot(x,v,dims=1) # create list of projection distances
      median = torch.median(distances)
      left_bool = distances <= median # create boolean array where entries are true if distance <= median
      right_bool = ~left_bool # inverse of left_bool
      left_indices = indices[left_bool]
      right_indices = indices[right_bool]
      self.make_tree(x[left_bool,:],left_indices, depth+1)
      self.make_tree(x[right_bool,:],right_indices, depth+1)
    elif x.shape[0] != 0:
      self.leaves.append(indices.tolist())
      self.sizes.append(x.shape[0])
    return

  def choose_rule(self, x):
    dim = x.shape[1]
    v = torch.rand(dim) # create random vector
    v /= torch.norm(v) # normalize to unit vector
    return v
    
def init_accuracy(data, graph, k_distances):
  '''
  Takes in data and graph to check accuracy of graph's assigned k nearest neighbours
  Uses torch brute force to find actual k nearest neighbours
  Returns accuracy: proportion of correct nearest neighbours
  Also returns distance error: (average_distance-true_distances)/true_distance (of k nearest neighbours)
  '''
  N, k = graph.shape

  # Calculate true distances, indices
  d=((data.unsqueeze(1)-data.unsqueeze(0))**2).sum(-1)+torch.Tensor([float('inf')]).repeat(len(data)).diag() # Infinity is added to diagonal
  true_distances, true_indices = torch.sort(d,dim=1)

  # get k nearest neighbours
  true_indices = true_indices[:,:k]
  true_distances = true_distances[:,:k]
  
  # Calculate number of correct nearest neighbours
  accuracy = 0
  for i in range(k):
    accuracy += torch.sum(graph == true_indices).float()
    true_indices = torch.roll(true_indices, 1, -1) # Create a rolling window (index positions may not match)
  accuracy = float(accuracy/(N*k)) # percentage accuracy

  # Calculate accuracy of distances
  true_average = torch.mean(true_distances)
  graph_average = torch.mean(k_distances)
  distance_error = float((graph_average-true_average)/true_average)

  return accuracy, distance_error

In [2]:
# Testing out NNDescent class
# torch.manual_seed(1)
data = torch.Tensor([[1.0,1.0], [2.0,1.0], [3.0,1.0], [4.0,1.0],
                     [1.0,2.0], [2.0,2.0], [3.0,2.0], [4.0,2.0]])  
data = torch.randn(size=[1000,4])
# print(data)  

torch.set_printoptions(threshold=10)

k = 5

# Initialize NNDescent graph randomly

print("Initializing RANDOMLY...")
start = time.time()
n = NNDescent(data, k=k, init=1)
print("Took", time.time()-start,"seconds.\n")
print("Graph:")
print(n.graph)
# print("Distances:")
print(torch.sqrt(n.k_distances))

print("Updating...\n")
start = time.time()
n.update_graph(iter=25)
print("Took", time.time()-start,"seconds.\n")
print("Graph:")
print(n.graph)
print("Distances:")
print(torch.sqrt(n.k_distances))
#print(n.k_distances)
accuracy, distance_error = init_accuracy(data, n.graph, n.k_distances)
print("Accuracy: ",accuracy)
print("Distance Error: ",distance_error,'\n')



# Initialize NNDescent graph with big random
print("Initializing BIG RANDOM...")
start = time.time()
n = NNDescent(data, k=k, init=2)
print("Took", time.time()-start,"seconds.\n")
print("Graph:")
print(n.graph)
print("Distances:")
print(torch.sqrt(n.k_distances))

print("Updating...\n")
start = time.time()
n.update_graph(iter=25)
print("Took", time.time()-start,"seconds.\n")
print("Graph:")
print(n.graph)
print("Distances:")
print(torch.sqrt(n.k_distances))
#print(n.k_distances)
accuracy, distance_error = init_accuracy(data, n.graph, n.k_distances)
print("Accuracy: ",accuracy)
print("Distance Error: ",distance_error,'\n')



# Initialize NNDescent graph with forest
print("Initializing FOREST...")
start = time.time()
n = NNDescent(data, k=k, init=3)
print("Took", time.time()-start,"seconds.\n")
print("Graph:")
print(n.graph)
print("Distances:")
print(torch.sqrt(n.k_distances))

print("Updating...\n")
start = time.time()
n.update_graph(iter=25)
print("Took", time.time()-start,"seconds.\n")
print("Graph:")
print(n.graph)
print("Distances:")
print(torch.sqrt(n.k_distances))
#print(n.k_distances)
accuracy, distance_error = init_accuracy(data, n.graph, n.k_distances)
print("Accuracy: ",accuracy)
print("Distance Error: ",distance_error,'\n')



# Brute force search
print("BRUTE FORCE")
start = time.time()
m=((data.unsqueeze(1)-data.unsqueeze(0))**2).sum(-1)#+torch.Tensor([float('inf')]).repeat(len(data)).diag() # Infinity is added to diagonal
distances, brute_force = torch.sort(m,dim=1)
brute_force = brute_force[:,1:k+1]
distances = distances[:,1:k+1]
  
print("Took", time.time()-start,"seconds.\n")
print(brute_force)
print('mean distance',(distances).sqrt().mean())
accuracy, distance_error = init_accuracy(data, brute_force, distances)
print("Accuracy: ",accuracy)
print("Distance Error: ",distance_error,'\n')

# Get k nearest neighbors using graph search
print()
print("Graph search")
#x = torch.Tensor([4, 0]).unsqueeze(0) # size 1 x d
X = torch.randn(size=[1000,data.shape[1]])
print("X is",X)
start = time.time()
k_nearest = n.k_nearest_graph_search(X)
print("Took", time.time()-start,"seconds.")
print("Nearest indices with graph search:\n",k_nearest)

print("K is",k)
# Get k nearest using brute force knn
print("\nActual nearest using KNN")
print("Brute force search:") # Crashes for 1 million points +
start = time.time()
m=((data.unsqueeze(0)-X.unsqueeze(1))**2).sum(-1)
distances, brute_force = torch.topk(m,k=k,dim=1,largest=False)
print("Took", time.time()-start,"seconds.")
print("Nearest indices with brute force:\n",brute_force)


Initializing RANDOMLY...
Took 0.16460466384887695 seconds.

Graph:
tensor([[359,  97, 948, 536, 322],
        [474, 295, 718, 221, 626],
        [281,  49, 284, 626, 707],
        ...,
        [514, 569, 841, 606, 346],
        [552, 876, 901, 688, 889],
        [797, 559, 186, 196, 388]])
tensor([[2.5608, 3.5315, 2.4899, 2.1834, 1.0654],
        [4.6182, 5.4265, 4.3821, 3.0470, 3.9578],
        [3.2383, 2.2863, 2.3856, 1.3753, 2.6563],
        ...,
        [3.5793, 4.3640, 2.8182, 4.3117, 5.2029],
        [1.5295, 1.3873, 2.7010, 1.4503, 2.8919],
        [1.5155, 2.8729, 2.3696, 2.5653, 2.6044]])
Updating...

Took 22.087337732315063 seconds.

Graph:
tensor([[720, 902, 926, 103, 784],
        [ 41,  95, 457, 979, 661],
        [366, 635,  42, 412, 253],
        ...,
        [425, 762, 529,  97,  73],
        [902, 327, 526, 511, 487],
        [425, 571, 838, 243, 762]])
Distances:
tensor([[0.5882, 0.6027, 0.7205, 0.8308, 0.8476],
        [2.2932, 2.3947, 2.3981, 2.4143, 2.5088],
      